# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_xbar_0/sub_BD_xbar_0.xci
# IP: The module: 'sub_BD_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_xbar_0/sub_BD_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_BD_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_xbar_0/sub_BD_xbar_0.xci
# IP: The module: 'sub_BD_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_xbar_0/sub_BD_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_BD_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
