# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/sub_BD_axi_smc_0.xci
# IP: The module: 'sub_BD_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/bd_936a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_48/bd_936a_s00a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_57/bd_936a_s01a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_63/bd_936a_s02a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_69/bd_936a_m00s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_75/bd_936a_m00e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_70/bd_936a_m00arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_71/bd_936a_m00rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_72/bd_936a_m00awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_73/bd_936a_m00wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_74/bd_936a_m00bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_64/bd_936a_sarn_5.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_65/bd_936a_srn_5.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_66/bd_936a_sawn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_67/bd_936a_swn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_68/bd_936a_sbn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_60/bd_936a_s02mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_61/bd_936a_s02tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_62/bd_936a_s02sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_58/bd_936a_sarn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_59/bd_936a_srn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_54/bd_936a_s01mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_55/bd_936a_s01tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_56/bd_936a_s01sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_49/bd_936a_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_50/bd_936a_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_51/bd_936a_sawn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_52/bd_936a_swn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_53/bd_936a_sbn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_45/bd_936a_s00mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_46/bd_936a_s00tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_47/bd_936a_s00sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_40/bd_936a_arsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_41/bd_936a_rsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_42/bd_936a_awsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_43/bd_936a_wsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_44/bd_936a_bsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_38/bd_936a_one_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_39/bd_936a_psr_aclk_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_48/bd_936a_s00a2s_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_57/bd_936a_s01a2s_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_63/bd_936a_s02a2s_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_69/bd_936a_m00s2a_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_70/bd_936a_m00arn_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_71/bd_936a_m00rn_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_72/bd_936a_m00awn_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_73/bd_936a_m00wn_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_74/bd_936a_m00bn_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_64/bd_936a_sarn_5_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_65/bd_936a_srn_5_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_66/bd_936a_sawn_3_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_67/bd_936a_swn_3_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_68/bd_936a_sbn_3_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_58/bd_936a_sarn_4_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_59/bd_936a_srn_4_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_49/bd_936a_sarn_3_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_50/bd_936a_srn_3_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_51/bd_936a_sawn_2_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_52/bd_936a_swn_2_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_53/bd_936a_sbn_2_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_40/bd_936a_arsw_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_41/bd_936a_rsw_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_42/bd_936a_awsw_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_43/bd_936a_wsw_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_44/bd_936a_bsw_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_39/bd_936a_psr_aclk_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_39/bd_936a_psr_aclk_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_BD_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: E:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/sub_BD_axi_smc_0.xci
# IP: The module: 'sub_BD_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/bd_936a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_48/bd_936a_s00a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_57/bd_936a_s01a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_63/bd_936a_s02a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_69/bd_936a_m00s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_75/bd_936a_m00e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_70/bd_936a_m00arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_71/bd_936a_m00rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_72/bd_936a_m00awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_73/bd_936a_m00wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_74/bd_936a_m00bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_64/bd_936a_sarn_5.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_65/bd_936a_srn_5.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_66/bd_936a_sawn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_67/bd_936a_swn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_68/bd_936a_sbn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_60/bd_936a_s02mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_61/bd_936a_s02tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_62/bd_936a_s02sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_58/bd_936a_sarn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_59/bd_936a_srn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_54/bd_936a_s01mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_55/bd_936a_s01tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_56/bd_936a_s01sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_49/bd_936a_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_50/bd_936a_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_51/bd_936a_sawn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_52/bd_936a_swn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_53/bd_936a_sbn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_45/bd_936a_s00mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_46/bd_936a_s00tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_47/bd_936a_s00sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_40/bd_936a_arsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_41/bd_936a_rsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_42/bd_936a_awsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_43/bd_936a_wsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_44/bd_936a_bsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_38/bd_936a_one_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_39/bd_936a_psr_aclk_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_48/bd_936a_s00a2s_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_57/bd_936a_s01a2s_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_63/bd_936a_s02a2s_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_69/bd_936a_m00s2a_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_70/bd_936a_m00arn_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_71/bd_936a_m00rn_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_72/bd_936a_m00awn_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_73/bd_936a_m00wn_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_74/bd_936a_m00bn_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_64/bd_936a_sarn_5_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_65/bd_936a_srn_5_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_66/bd_936a_sawn_3_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_67/bd_936a_swn_3_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_68/bd_936a_sbn_3_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_58/bd_936a_sarn_4_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_59/bd_936a_srn_4_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_49/bd_936a_sarn_3_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_50/bd_936a_srn_3_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_51/bd_936a_sawn_2_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_52/bd_936a_swn_2_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_53/bd_936a_sbn_2_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_40/bd_936a_arsw_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_41/bd_936a_rsw_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_42/bd_936a_awsw_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_43/bd_936a_wsw_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_44/bd_936a_bsw_1_ooc.xdc

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_39/bd_936a_psr_aclk_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_39/bd_936a_psr_aclk_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Xilinx/XD58_Project/XD58/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_BD_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
