# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_wr_ddr3_ip/FIFO_wr_ddr3_ip.xci
# IP: The module: 'FIFO_wr_ddr3_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_wr_ddr3_ip/FIFO_wr_ddr3_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_wr_ddr3_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_wr_ddr3_ip/FIFO_wr_ddr3_ip_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_wr_ddr3_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_wr_ddr3_ip/FIFO_wr_ddr3_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_wr_ddr3_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_wr_ddr3_ip/FIFO_wr_ddr3_ip.xci
# IP: The module: 'FIFO_wr_ddr3_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_wr_ddr3_ip/FIFO_wr_ddr3_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_wr_ddr3_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_wr_ddr3_ip/FIFO_wr_ddr3_ip_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_wr_ddr3_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_wr_ddr3_ip/FIFO_wr_ddr3_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_wr_ddr3_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
