create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sub_BD_inst/sub_BD_i/mig_7series_0/u_sub_BD_mig_7series_0_1_mig/u_ddr3_infrastructure/ui_clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 6 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {ddr3_block_inst/wr_ddr3_data_sel/state_a_w[0]} {ddr3_block_inst/wr_ddr3_data_sel/state_a_w[1]} {ddr3_block_inst/wr_ddr3_data_sel/state_a_w[2]} {ddr3_block_inst/wr_ddr3_data_sel/state_a_w[3]} {ddr3_block_inst/wr_ddr3_data_sel/state_a_w[4]} {ddr3_block_inst/wr_ddr3_data_sel/state_a_w[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_w[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_over_addr_par_w[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 11 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[0]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[1]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[2]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[3]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[4]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[5]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[6]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[7]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[8]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[9]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[10]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 6 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/state_a_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/state_a_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/state_a_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/state_a_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/state_a_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/state_a_w[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_par_w[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 32 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_start_addr_w[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list ddr3_block_inst/wr_ddr3_data_sel/ch_A_ok_w]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/ddr3_wr_done_w]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_ddr3_data_en_w]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_time_code_en_w]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/rden_sel_w]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/txn_done_w]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list ddr3_block_inst/wr_ddr3_data_sel/type_A0_ok_w]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list ddr3_block_inst/wr_ddr3_data_sel/type_A1_ok_w]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_rd_data_en_w]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_en_w]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_satisfy_w]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_ddr3_ch_sel_w]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_100M]
