# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Project_top.xdc

# XDC: new/DDR3.xdc

# XDC: new/debug.xdc

# Block Designs: bd/sub_BD/sub_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD || ORIG_REF_NAME==sub_BD}]

# IP: bd/sub_BD/ip/sub_BD_MY_AXI_MASTER_FULL_ip_0_1/sub_BD_MY_AXI_MASTER_FULL_ip_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_MY_AXI_MASTER_FULL_ip_0_1 || ORIG_REF_NAME==sub_BD_MY_AXI_MASTER_FULL_ip_0_1}]

# IP: bd/sub_BD/ip/sub_BD_mig_7series_0_1/sub_BD_mig_7series_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_mig_7series_0_1 || ORIG_REF_NAME==sub_BD_mig_7series_0_1}]

# IP: bd/sub_BD/ip/sub_BD_microblaze_0_0/sub_BD_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_microblaze_0_0 || ORIG_REF_NAME==sub_BD_microblaze_0_0}]

# IP: bd/sub_BD/ip/sub_BD_microblaze_0_axi_periph_0/sub_BD_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_microblaze_0_axi_periph_0 || ORIG_REF_NAME==sub_BD_microblaze_0_axi_periph_0}]

# IP: bd/sub_BD/ip/sub_BD_microblaze_0_axi_intc_0/sub_BD_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_microblaze_0_axi_intc_0 || ORIG_REF_NAME==sub_BD_microblaze_0_axi_intc_0}]

# IP: bd/sub_BD/ip/sub_BD_microblaze_0_xlconcat_0/sub_BD_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_microblaze_0_xlconcat_0 || ORIG_REF_NAME==sub_BD_microblaze_0_xlconcat_0}]

# IP: bd/sub_BD/ip/sub_BD_mdm_1_0/sub_BD_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_mdm_1_0 || ORIG_REF_NAME==sub_BD_mdm_1_0}]

# IP: bd/sub_BD/ip/sub_BD_rst_mig_7series_0_83M_0/sub_BD_rst_mig_7series_0_83M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==sub_BD_rst_mig_7series_0_83M_0}]

# IP: bd/sub_BD/ip/sub_BD_axi_timer_0_0/sub_BD_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_axi_timer_0_0 || ORIG_REF_NAME==sub_BD_axi_timer_0_0}]

# IP: bd/sub_BD/ip/sub_BD_axi_uartlite_0_0/sub_BD_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_axi_uartlite_0_0 || ORIG_REF_NAME==sub_BD_axi_uartlite_0_0}]

# IP: bd/sub_BD/ip/sub_BD_axi_ethernetlite_0_0/sub_BD_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_axi_ethernetlite_0_0 || ORIG_REF_NAME==sub_BD_axi_ethernetlite_0_0}]

# IP: bd/sub_BD/ip/sub_BD_axi_smc_0/sub_BD_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_axi_smc_0 || ORIG_REF_NAME==sub_BD_axi_smc_0}]

# IP: bd/sub_BD/ip/sub_BD_xbar_0/sub_BD_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_xbar_0 || ORIG_REF_NAME==sub_BD_xbar_0}]

# IP: bd/sub_BD/ip/sub_BD_dlmb_v10_0/sub_BD_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_dlmb_v10_0 || ORIG_REF_NAME==sub_BD_dlmb_v10_0}]

# IP: bd/sub_BD/ip/sub_BD_ilmb_v10_0/sub_BD_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_ilmb_v10_0 || ORIG_REF_NAME==sub_BD_ilmb_v10_0}]

# IP: bd/sub_BD/ip/sub_BD_dlmb_bram_if_cntlr_0/sub_BD_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==sub_BD_dlmb_bram_if_cntlr_0}]

# IP: bd/sub_BD/ip/sub_BD_ilmb_bram_if_cntlr_0/sub_BD_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==sub_BD_ilmb_bram_if_cntlr_0}]

# IP: bd/sub_BD/ip/sub_BD_lmb_bram_0/sub_BD_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_BD_lmb_bram_0 || ORIG_REF_NAME==sub_BD_lmb_bram_0}]

# IP: ip/FIFO_time_code_ip/FIFO_time_code_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_time_code_ip || ORIG_REF_NAME==FIFO_time_code_ip}]

# IP: ip/FIFO_AD_ip/FIFO_AD_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_AD_ip || ORIG_REF_NAME==FIFO_AD_ip}]

# IP: ip/PLL_ip/PLL_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLL_ip || ORIG_REF_NAME==PLL_ip}]

# XDC: bd/sub_BD/sub_BD_ooc.xdc

# XDC: ip/PLL_ip/PLL_ip_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PLL_ip || ORIG_REF_NAME==PLL_ip}] {/inst }]/inst ]]

# XDC: ip/PLL_ip/PLL_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PLL_ip || ORIG_REF_NAME==PLL_ip}] {/inst }]/inst ]]

# XDC: ip/PLL_ip/PLL_ip_ooc.xdc
