# 
# Synthesis run script generated by Vivado
# 

set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/XD58_test/XD58_Artix_100T_project/Project.cache/wt [current_project]
set_property parent.project_path C:/XD58_test/XD58_Artix_100T_project/Project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/Xilinx/XD58_Project/My_ip_module
  c:/XD58_test/project_xd58/project_xd58.srcs
} [current_project]
set_property ip_output_repo c:/XD58_test/XD58_Artix_100T_project/Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/tt.coe
read_verilog -library xil_defaultlib {
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/ADC_module.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/AD_deal_block.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/AD_fifo_rd_ctrl.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/AD_frame.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/Ch_data_deal_block.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/FIFO_series_block.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/ad_data_sample.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/clk_domain_cov.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/data_convert.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/ddr3_block.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/par_updata.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/rd_ddr3_ctrl.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/series_data_ctrl.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/series_data_gather.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/series_data_gather_block.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/hdl/sub_BD_wrapper.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/system_rstn.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/test_vio.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/wr_ddr3_ctrl.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/wr_ddr3_ctrl_block.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/wr_ddr3_data_sel.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/zero_calibrate.v
  C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/new/Project_top.v
}
add_files C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/sub_BD.bd
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_mig_7series_0_1/sub_BD_mig_7series_0_1/user_design/constraints/sub_BD_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_mig_7series_0_1/sub_BD_mig_7series_0_1/user_design/constraints/sub_BD_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_microblaze_0_0/sub_BD_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_microblaze_0_0/sub_BD_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_microblaze_0_0/sub_BD_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_microblaze_0_axi_intc_0/sub_BD_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_microblaze_0_axi_intc_0/sub_BD_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_microblaze_0_axi_intc_0/sub_BD_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_mdm_1_0/sub_BD_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_mdm_1_0/sub_BD_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_rst_mig_7series_0_83M_0/sub_BD_rst_mig_7series_0_83M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_rst_mig_7series_0_83M_0/sub_BD_rst_mig_7series_0_83M_0.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_rst_mig_7series_0_83M_0/sub_BD_rst_mig_7series_0_83M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_timer_0_0/sub_BD_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_timer_0_0/sub_BD_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_uartlite_0_0/sub_BD_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_uartlite_0_0/sub_BD_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_uartlite_0_0/sub_BD_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_ethernetlite_0_0/sub_BD_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_ethernetlite_0_0/sub_BD_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_ethernetlite_0_0/sub_BD_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_ethernetlite_0_0/sub_BD_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_10/bd_936a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_19/bd_936a_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_25/bd_936a_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_31/bd_936a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_32/bd_936a_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_33/bd_936a_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_34/bd_936a_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_35/bd_936a_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_36/bd_936a_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_26/bd_936a_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_27/bd_936a_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_28/bd_936a_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_29/bd_936a_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_30/bd_936a_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_20/bd_936a_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_21/bd_936a_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_11/bd_936a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_12/bd_936a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_13/bd_936a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_14/bd_936a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_15/bd_936a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_2/bd_936a_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_3/bd_936a_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_4/bd_936a_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_5/bd_936a_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_6/bd_936a_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_1/bd_936a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/bd_0/ip/ip_1/bd_936a_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_xbar_0/sub_BD_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_dlmb_v10_0/sub_BD_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_dlmb_v10_0/sub_BD_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_ilmb_v10_0/sub_BD_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_ilmb_v10_0/sub_BD_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_dlmb_bram_if_cntlr_0/sub_BD_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_ilmb_bram_if_cntlr_0/sub_BD_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/ip/sub_BD_lmb_bram_0/sub_BD_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/sub_BD_ooc.xdc]
set_property is_locked true [get_files C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/bd/sub_BD/sub_BD.bd]

read_ip -quiet C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_time_code_ip/FIFO_time_code_ip.xci
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_time_code_ip/FIFO_time_code_ip.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_time_code_ip/FIFO_time_code_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_time_code_ip/FIFO_time_code_ip_ooc.xdc]
set_property is_locked true [get_files C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_time_code_ip/FIFO_time_code_ip.xci]

read_ip -quiet C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_AD_ip/FIFO_AD_ip.xci
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_AD_ip/FIFO_AD_ip.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_AD_ip/FIFO_AD_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_AD_ip/FIFO_AD_ip_ooc.xdc]
set_property is_locked true [get_files C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_AD_ip/FIFO_AD_ip.xci]

read_ip -quiet C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/PLL_ip/PLL_ip.xci
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/PLL_ip/PLL_ip_board.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/PLL_ip/PLL_ip.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/PLL_ip/PLL_ip_ooc.xdc]
set_property is_locked true [get_files C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/PLL_ip/PLL_ip.xci]

read_ip -quiet C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/vio_0/vio_0.xci
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/vio_0/vio_0.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/vio_0/vio_0_ooc.xdc]
set_property is_locked true [get_files C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/vio_0/vio_0.xci]

read_ip -quiet C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_wr_ddr3_ip/FIFO_wr_ddr3_ip.xci
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_wr_ddr3_ip/FIFO_wr_ddr3_ip.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_wr_ddr3_ip/FIFO_wr_ddr3_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_wr_ddr3_ip/FIFO_wr_ddr3_ip_ooc.xdc]
set_property is_locked true [get_files C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/FIFO_wr_ddr3_ip/FIFO_wr_ddr3_ip.xci]

read_ip -quiet C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/isa_handle_0.xci
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_get_fifo_generator/isa_get_fifo_generator.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_rom_generator/isa_send_rom_generator_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_smallram_generator/isa_send_smallram_generator_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_bigram_generator/isa_send_bigram_generator_ooc.xdc]
set_property is_locked true [get_files C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/isa_handle_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/XD58_test/XD58_Artix_100T_project/Project.srcs/constrs_1/new/Project_top.xdc
set_property used_in_implementation false [get_files C:/XD58_test/XD58_Artix_100T_project/Project.srcs/constrs_1/new/Project_top.xdc]

read_xdc C:/XD58_test/XD58_Artix_100T_project/Project.srcs/constrs_1/new/DDR3.xdc
set_property used_in_implementation false [get_files C:/XD58_test/XD58_Artix_100T_project/Project.srcs/constrs_1/new/DDR3.xdc]

read_xdc C:/XD58_test/XD58_Artix_100T_project/Project.srcs/constrs_1/new/debug.xdc
set_property used_in_implementation false [get_files C:/XD58_test/XD58_Artix_100T_project/Project.srcs/constrs_1/new/debug.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Project_top -part xc7a100tfgg484-2L


write_checkpoint -force -noxdef Project_top.dcp

catch { report_utilization -file Project_top_utilization_synth.rpt -pb Project_top_utilization_synth.pb }
