set_property SRC_FILE_INFO {cfile:c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/PLL_ip/PLL_ip.xdc rfile:../../../Project.srcs/sources_1/ip/PLL_ip/PLL_ip.xdc id:1 order:EARLY scoped_inst:PLL_ip_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/XD58_test/XD58_Artix_100T_project/Project.srcs/constrs_1/new/Project_top.xdc rfile:../../../Project.srcs/constrs_1/new/Project_top.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/XD58_test/XD58_Artix_100T_project/Project.srcs/constrs_1/new/DDR3.xdc rfile:../../../Project.srcs/constrs_1/new/DDR3.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:C:/XD58_test/XD58_Artix_100T_project/Project.srcs/constrs_1/new/debug.xdc rfile:../../../Project.srcs/constrs_1/new/debug.xdc id:4} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.4
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports clk_in]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R4 [get_ports ddr3_addr_h]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports ddr3_cs_n]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P2 [get_ports ad_clk_out_p]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N2 [get_ports ad_clk_out_n]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H2 [get_ports DCO_p]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G2 [get_ports DCO_n]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G1 [get_ports FCO_p]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F1 [get_ports FCO_n]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C2 [get_ports D0_A_p]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B2 [get_ports D0_A_n]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E2 [get_ports D1_A_p]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D2 [get_ports D1_A_n]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E1 [get_ports D0_B_p]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D1 [get_ports D0_B_n]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F3 [get_ports D1_B_p]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports D1_B_n]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports D0_C_p]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J2 [get_ports D0_C_n]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K1 [get_ports D1_C_p]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports D1_C_n]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports D0_D_p]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K3 [get_ports D0_D_n]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports D1_D_n]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports D1_D_p]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports mdio_rtl_mdio_io]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports mdio_rtl_mdc]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB15 [get_ports mii_rtl_col]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB16 [get_ports mii_rtl_crs]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB17 [get_ports mii_rtl_rx_clk]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports mii_rtl_rx_dv]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA16 [get_ports mii_rtl_rx_er]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA15 [get_ports {mii_rtl_rxd[0]}]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA14 [get_ports {mii_rtl_rxd[1]}]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB13 [get_ports {mii_rtl_rxd[2]}]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA13 [get_ports {mii_rtl_rxd[3]}]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA11 [get_ports mii_rtl_tx_en]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB12 [get_ports mii_rtl_tx_clk]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB11 [get_ports {mii_rtl_txd[0]}]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA10 [get_ports {mii_rtl_txd[1]}]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB10 [get_ports {mii_rtl_txd[2]}]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA9 [get_ports {mii_rtl_txd[3]}]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports eth_ref_clk]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y14 [get_ports mii_rtl_rst_n]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B21 [get_ports uart_rtl_rxd]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A21 [get_ports uart_rtl_txd]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15 [get_ports pin_isa_adv]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E14 [get_ports pin_isa_cs]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15 [get_ports pin_isa_rd]
set_property src_info {type:XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D15 [get_ports pin_isa_wr]
set_property src_info {type:XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C15 [get_ports {pin_isa_data[7]}]
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D17 [get_ports {pin_isa_data[6]}]
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C18 [get_ports {pin_isa_data[5]}]
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C19 [get_ports {pin_isa_data[4]}]
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports {pin_isa_data[3]}]
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports {pin_isa_data[2]}]
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F16 [get_ports {pin_isa_data[1]}]
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20 [get_ports {pin_isa_data[0]}]
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -of_objects [get_pins PLL_ip_inst/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins sub_BD_inst/sub_BD_i/mig_7series_0/u_sub_BD_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -of_objects [get_pins sub_BD_inst/sub_BD_i/mig_7series_0/u_sub_BD_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins PLL_ip_inst/inst/mmcm_adv_inst/CLKOUT1]]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[15]}]
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL135 [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL135 [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_cke[0]}]
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_odt[0]}]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA3 [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y3 [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA6 [get_ports {ddr3_dm[0]}]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB3 [get_ports {ddr3_dm[1]}]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W2 [get_ports {ddr3_odt[0]}]
set_property src_info {type:XDC file:3 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports ddr3_reset_n]
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports {ddr3_dq[0]}]
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports {ddr3_dq[1]}]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports {ddr3_dq[2]}]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports {ddr3_dq[3]}]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {ddr3_dq[4]}]
set_property src_info {type:XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R6 [get_ports {ddr3_dq[5]}]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports {ddr3_dq[6]}]
set_property src_info {type:XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y6 [get_ports {ddr3_dq[7]}]
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y4 [get_ports {ddr3_dq[8]}]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W4 [get_ports {ddr3_dq[9]}]
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA5 [get_ports {ddr3_dq[10]}]
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB2 [get_ports {ddr3_dq[11]}]
set_property src_info {type:XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA4 [get_ports {ddr3_dq[12]}]
set_property src_info {type:XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA1 [get_ports {ddr3_dq[13]}]
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB5 [get_ports {ddr3_dq[14]}]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB1 [get_ports {ddr3_dq[15]}]
set_property src_info {type:XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3 [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:XDC file:3 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y1 [get_ports ddr3_cas_n]
set_property src_info {type:XDC file:3 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports {ddr3_cke[0]}]
set_property src_info {type:XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y2 [get_ports ddr3_ras_n]
set_property src_info {type:XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W1 [get_ports ddr3_we_n]
set_property src_info {type:XDC file:3 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V3 [get_ports {ddr3_ba[0]}]
set_property src_info {type:XDC file:3 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports {ddr3_ba[1]}]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2 [get_ports {ddr3_ba[2]}]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8 [get_ports {ddr3_addr[0]}]
set_property src_info {type:XDC file:3 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports {ddr3_addr[1]}]
set_property src_info {type:XDC file:3 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8 [get_ports {ddr3_addr[2]}]
set_property src_info {type:XDC file:3 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3 [get_ports {ddr3_addr[3]}]
set_property src_info {type:XDC file:3 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W9 [get_ports {ddr3_addr[4]}]
set_property src_info {type:XDC file:3 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports {ddr3_addr[5]}]
set_property src_info {type:XDC file:3 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB6 [get_ports {ddr3_addr[6]}]
set_property src_info {type:XDC file:3 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports {ddr3_addr[7]}]
set_property src_info {type:XDC file:3 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y7 [get_ports {ddr3_addr[8]}]
set_property src_info {type:XDC file:3 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports {ddr3_addr[9]}]
set_property src_info {type:XDC file:3 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W7 [get_ports {ddr3_addr[10]}]
set_property src_info {type:XDC file:3 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {ddr3_addr[11]}]
set_property src_info {type:XDC file:3 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports {ddr3_addr[12]}]
set_property src_info {type:XDC file:3 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports {ddr3_addr[13]}]
set_property src_info {type:XDC file:3 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB7 [get_ports {ddr3_addr[14]}]
set_property src_info {type:XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:4 line:11 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list sub_BD_inst/sub_BD_i/mig_7series_0/u_sub_BD_mig_7series_0_1_mig/u_ddr3_infrastructure/ui_clk]]
set_property src_info {type:XDC file:4 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:4 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:4 line:14 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_len_w[15]}]]
set_property src_info {type:XDC file:4 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:4 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:4 line:18 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/state_a_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/state_a_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/state_a_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/state_a_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/state_a_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/state_a_w[5]}]]
set_property src_info {type:XDC file:4 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:4 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_burst_len_w[7]}]]
set_property src_info {type:XDC file:4 line:23 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:4 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:4 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_base_addr_w[31]}]]
set_property src_info {type:XDC file:4 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:4 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:4 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_addr_step_w[31]}]]
set_property src_info {type:XDC file:4 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:4 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:4 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_data_w[31]}]]
set_property src_info {type:XDC file:4 line:35 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:4 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:4 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {ddr3_block_inst/wr_ddr3_data_sel/state_a_w[0]} {ddr3_block_inst/wr_ddr3_data_sel/state_a_w[1]} {ddr3_block_inst/wr_ddr3_data_sel/state_a_w[2]} {ddr3_block_inst/wr_ddr3_data_sel/state_a_w[3]} {ddr3_block_inst/wr_ddr3_data_sel/state_a_w[4]} {ddr3_block_inst/wr_ddr3_data_sel/state_a_w[5]}]]
set_property src_info {type:XDC file:4 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:4 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 11 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:4 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[0]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[1]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[2]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[3]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[4]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[5]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[6]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[7]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[8]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[9]} {ddr3_block_inst/wr_ddr3_data_sel/fifo_ddr3_sgl_A_w[10]}]]
set_property src_info {type:XDC file:4 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:4 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:4 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_time_code_w[31]}]]
set_property src_info {type:XDC file:4 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:4 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:4 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_temp_addr_w[31]}]]
set_property src_info {type:XDC file:4 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:4 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:4 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[0]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[1]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[2]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[3]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[4]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[5]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[6]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[7]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[8]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[9]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[10]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[11]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[12]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[13]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[14]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[15]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[16]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[17]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[18]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[19]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[20]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[21]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[22]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[23]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[24]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[25]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[26]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[27]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[28]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[29]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[30]} {ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_data_w[31]}]]
set_property src_info {type:XDC file:4 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:4 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:4 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list ddr3_block_inst/wr_ddr3_data_sel/ch_A_ok_w]]
set_property src_info {type:XDC file:4 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:4 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:4 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/ddr3_wr_done_w]]
set_property src_info {type:XDC file:4 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:4 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:4 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_ddr3_data_en_w]]
set_property src_info {type:XDC file:4 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:4 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:4 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/fifo_rd_time_code_en_w]]
set_property src_info {type:XDC file:4 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:4 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:4 line:74 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/rden_sel_w]]
set_property src_info {type:XDC file:4 line:75 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:4 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:4 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/txn_done_w]]
set_property src_info {type:XDC file:4 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:4 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:4 line:82 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list ddr3_block_inst/wr_ddr3_data_sel/type_A0_ok_w]]
set_property src_info {type:XDC file:4 line:83 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:4 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:4 line:86 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list ddr3_block_inst/wr_ddr3_data_sel/type_A1_ok_w]]
set_property src_info {type:XDC file:4 line:87 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:4 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:4 line:90 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_rd_data_en_w]]
set_property src_info {type:XDC file:4 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:4 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:4 line:94 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_en_w]]
set_property src_info {type:XDC file:4 line:95 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:4 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:4 line:98 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/user_wr_satisfy_w]]
set_property src_info {type:XDC file:4 line:99 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:4 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:4 line:102 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list ddr3_block_inst/wr_ddr3_ctrl_block/wr_ddr3_ctrl_A/wr_ddr3_ch_sel_w]]
set_property src_info {type:XDC file:4 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:106 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk_100M]
