-- Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2017.2 (win64) Build 1909853 Thu Jun 15 18:39:09 MDT 2017
-- Date        : Sat Nov 18 15:20:51 2017
-- Host        : Fred-PC running 64-bit Service Pack 1  (build 7601)
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ ISA_handle_ip_stub.vhdl
-- Design      : ISA_handle_ip
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7a100tfgg484-2L
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    reset : in STD_LOGIC;
    clk : in STD_LOGIC;
    pin_isa_cs : in STD_LOGIC;
    pin_isa_wr : in STD_LOGIC;
    pin_isa_rd : in STD_LOGIC;
    pin_isa_adv : in STD_LOGIC;
    pin_isa_data : inout STD_LOGIC_VECTOR ( 7 downto 0 );
    rreg_system_debug1 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rreg_system_debug1_valid : in STD_LOGIC;
    rreg_system_debug2 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rreg_system_debug2_valid : in STD_LOGIC;
    rreg_system_debug3 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rreg_system_debug3_valid : in STD_LOGIC;
    rreg_system_debug4 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rreg_system_debug4_valid : in STD_LOGIC;
    rreg_system_status : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rreg_system_status_valid : in STD_LOGIC;
    rreg_system_version : in STD_LOGIC_VECTOR ( 47 downto 0 );
    rreg_system_version_valid : in STD_LOGIC;
    rreg_system_rtctime : in STD_LOGIC_VECTOR ( 63 downto 0 );
    rreg_system_rtctime_valid : in STD_LOGIC;
    rreg_system_batteryvalue : in STD_LOGIC_VECTOR ( 15 downto 0 );
    rreg_system_batteryvalue_valid : in STD_LOGIC;
    rreg_system_syncstatus : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rreg_system_syncstatus_valid : in STD_LOGIC;
    rreg_system_syncfrq : in STD_LOGIC_VECTOR ( 31 downto 0 );
    rreg_system_syncfrq_valid : in STD_LOGIC;
    rreg_mem_status : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rreg_mem_status_valid : in STD_LOGIC;
    rreg_mem_data_wr_en : in STD_LOGIC;
    rreg_mem_data_wr_addr : in STD_LOGIC_VECTOR ( 15 downto 0 );
    rreg_mem_data_wr_data : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rreg_ddr_status : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rreg_ddr_status_valid : in STD_LOGIC;
    rreg_ddr_data_wr_en : in STD_LOGIC;
    rreg_ddr_data_wr_addr : in STD_LOGIC_VECTOR ( 15 downto 0 );
    rreg_ddr_data_wr_data : in STD_LOGIC_VECTOR ( 31 downto 0 );
    rreg_series_status : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rreg_series_status_valid : in STD_LOGIC;
    rreg_series_starttime : in STD_LOGIC_VECTOR ( 63 downto 0 );
    rreg_series_starttime_valid : in STD_LOGIC;
    rreg_series_stoptime : in STD_LOGIC_VECTOR ( 63 downto 0 );
    rreg_series_stoptime_valid : in STD_LOGIC;
    rreg_series_maxdata : in STD_LOGIC_VECTOR ( 79 downto 0 );
    rreg_series_maxdata_valid : in STD_LOGIC;
    rreg_series_data_wr_en : in STD_LOGIC;
    rreg_series_data_wr_addr : in STD_LOGIC_VECTOR ( 15 downto 0 );
    rreg_series_data_wr_data : in STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_system_ctrl : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_system_ctrl_valid : out STD_LOGIC;
    wreg_system_sel_rtc : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_system_sel_rtc_valid : out STD_LOGIC;
    wreg_system_set_rtctime : out STD_LOGIC_VECTOR ( 63 downto 0 );
    wreg_system_set_rtctime_valid : out STD_LOGIC;
    wreg_system_sync_minfrq : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_system_sync_minfrq_valid : out STD_LOGIC;
    wreg_system_sync_max : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_system_sync_max_valid : out STD_LOGIC;
    wreg_system_sync_sel : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_system_sync_sel_valid : out STD_LOGIC;
    wreg_system_ch_sel : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_system_ch_sel_valid : out STD_LOGIC;
    wreg_ddr_ctrl : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_ddr_ctrl_valid : out STD_LOGIC;
    wreg_ddr_addr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_ddr_addr_valid : out STD_LOGIC;
    wreg_ddr_len : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_ddr_len_valid : out STD_LOGIC;
    wreg_out_ctrl : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_out_ctrl_valid : out STD_LOGIC;
    wreg_out_sel : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_out_sel_valid : out STD_LOGIC;
    wreg_out_time : out STD_LOGIC_VECTOR ( 63 downto 0 );
    wreg_out_time_valid : out STD_LOGIC;
    wreg_out_level : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_out_level_valid : out STD_LOGIC;
    wreg_out_startmode : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_out_startmode_valid : out STD_LOGIC;
    wreg_out_start_targettime : out STD_LOGIC_VECTOR ( 63 downto 0 );
    wreg_out_start_targettime_valid : out STD_LOGIC;
    wreg_out_start_subtime : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_out_start_subtime_valid : out STD_LOGIC;
    wreg_out_start_subnum : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_out_start_subnum_valid : out STD_LOGIC;
    wreg_out_start_subcycle : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_out_start_subcycle_valid : out STD_LOGIC;
    wreg_out_start_trigmode1 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_out_start_trigmode1_valid : out STD_LOGIC;
    wreg_out_start_trigmode2 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_out_start_trigmode2_valid : out STD_LOGIC;
    wreg_out_start_trigmode3 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_out_start_trigmode3_valid : out STD_LOGIC;
    wreg_out_start_trigmode4 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_out_start_trigmode4_valid : out STD_LOGIC;
    wreg_out_trig_threshold_p : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_out_trig_threshold_p_valid : out STD_LOGIC;
    wreg_out_trig_threshold_n : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_out_trig_threshold_n_valid : out STD_LOGIC;
    wreg_out_trig_risetime : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_out_trig_risetime_valid : out STD_LOGIC;
    wreg_out_trig_droptime : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_out_trig_droptime_valid : out STD_LOGIC;
    wreg_out_trig_pulsewidth : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_out_trig_pulsewidth_valid : out STD_LOGIC;
    wreg_out_trig_riseratio : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_out_trig_riseratio_valid : out STD_LOGIC;
    wreg_out_trig_dropratio : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_out_trig_dropratio_valid : out STD_LOGIC;
    wreg_out_trig_rmsvalue : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_out_trig_rmsvalue_valid : out STD_LOGIC;
    wreg_mem_rd_en : in STD_LOGIC;
    wreg_mem_ctrl : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_mem_ctrl_valid : out STD_LOGIC;
    wreg_mem_addr : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_mem_addr_valid : out STD_LOGIC;
    wreg_mem_len : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_mem_len_valid : out STD_LOGIC;
    wreg_mem_clr : out STD_LOGIC;
    wreg_mem_rd_data : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_mem_rd_len : out STD_LOGIC_VECTOR ( 3 downto 0 );
    wreg_ch_zero_cal : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_ch_zero_cal_valid : out STD_LOGIC;
    wreg_ch_sample_rate : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_ch_sample_rate_valid : out STD_LOGIC;
    wreg_ch_sign_handle : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_ch_sign_handle_valid : out STD_LOGIC;
    wreg_ch_main_amp : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_ch_main_amp_valid : out STD_LOGIC;
    wreg_ch_pre_amp : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_ch_pre_amp_valid : out STD_LOGIC;
    wreg_ch_v_amp : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_ch_v_amp_valid : out STD_LOGIC;
    wreg_ch_i_amp : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_ch_i_amp_valid : out STD_LOGIC;
    wreg_ch_noise_comp : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_ch_noise_comp_valid : out STD_LOGIC;
    wreg_ch_noise_amp_cof : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_ch_noise_amp_cof_valid : out STD_LOGIC;
    wreg_ch_noise_delay : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_ch_noise_delay_valid : out STD_LOGIC;
    wreg_ch_start_targettime : out STD_LOGIC_VECTOR ( 63 downto 0 );
    wreg_ch_start_targettime_valid : out STD_LOGIC;
    wreg_ch_start_sustime : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_ch_start_sustime_valid : out STD_LOGIC;
    wreg_ch_start_susnum : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_ch_start_susnum_valid : out STD_LOGIC;
    wreg_ch_start_suscycle : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_ch_start_suscycle_valid : out STD_LOGIC;
    wreg_ch_stop_sustime : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_ch_stop_sustime_valid : out STD_LOGIC;
    wreg_ch_stop_susnum : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_ch_stop_susnum_valid : out STD_LOGIC;
    wreg_ch_stop_suscycle : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_ch_stop_suscycle_valid : out STD_LOGIC;
    wreg_ch_trig_threshold_p : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_ch_trig_threshold_p_valid : out STD_LOGIC;
    wreg_ch_trig_threshold_n : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_ch_trig_threshold_n_valid : out STD_LOGIC;
    wreg_ch_trig_risetime : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_ch_trig_risetime_valid : out STD_LOGIC;
    wreg_ch_trig_droptime : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_ch_trig_droptime_valid : out STD_LOGIC;
    wreg_ch_trig_pulsewidth : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_ch_trig_pulsewidth_valid : out STD_LOGIC;
    wreg_ch_trig_riseratio : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_ch_trig_riseratio_valid : out STD_LOGIC;
    wreg_ch_trig_dropratio : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_ch_trig_dropratio_valid : out STD_LOGIC;
    wreg_ch_trig_rmsvalue : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_ch_trig_rmsvalue_valid : out STD_LOGIC;
    wreg_ch_filter_rd_en : in STD_LOGIC;
    wreg_ch_filter_clr : out STD_LOGIC;
    wreg_ch_filter_rd_data : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_ch_filter_rd_len : out STD_LOGIC_VECTOR ( 3 downto 0 );
    wreg_series_ctrl : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_series_ctrl_valid : out STD_LOGIC;
    wreg_series_data_type : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_series_data_type_valid : out STD_LOGIC;
    wreg_series_sample_cycle : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_series_sample_cycle_valid : out STD_LOGIC;
    wreg_series_comp_ratio : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_series_comp_ratio_valid : out STD_LOGIC;
    wreg_series_comp_num : out STD_LOGIC_VECTOR ( 15 downto 0 );
    wreg_series_comp_num_valid : out STD_LOGIC;
    wreg_series_validmode_data : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_series_validmode_data_valid : out STD_LOGIC;
    wreg_series_start_ddraddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_series_start_ddraddr_valid : out STD_LOGIC;
    wreg_series_stop_ddraddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_series_stop_ddraddr_valid : out STD_LOGIC;
    wreg_series_startmode : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_series_startmode_valid : out STD_LOGIC;
    wreg_series_star_trigmode1 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_series_star_trigmode1_valid : out STD_LOGIC;
    wreg_series_star_trigmode2 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_series_star_trigmode2_valid : out STD_LOGIC;
    wreg_series_star_trigmode3 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_series_star_trigmode3_valid : out STD_LOGIC;
    wreg_series_star_trigmode4 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_series_star_trigmode4_valid : out STD_LOGIC;
    wreg_series_stopmode : out STD_LOGIC_VECTOR ( 7 downto 0 );
    wreg_series_stopmode_valid : out STD_LOGIC;
    wreg_series_stop_trigmode1 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_series_stop_trigmode1_valid : out STD_LOGIC;
    wreg_series_stop_trigmode2 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_series_stop_trigmode2_valid : out STD_LOGIC;
    wreg_series_stop_trigmode3 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_series_stop_trigmode3_valid : out STD_LOGIC;
    wreg_series_stop_trigmode4 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_series_stop_trigmode4_valid : out STD_LOGIC;
    wreg_series_seek_startime : out STD_LOGIC_VECTOR ( 63 downto 0 );
    wreg_series_seek_startime_valid : out STD_LOGIC;
    wreg_series_seek_zoom : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_series_seek_zoom_valid : out STD_LOGIC;
    wreg_series_seek_datalen : out STD_LOGIC_VECTOR ( 31 downto 0 );
    wreg_series_seek_datalen_valid : out STD_LOGIC
  );

end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "reset,clk,pin_isa_cs,pin_isa_wr,pin_isa_rd,pin_isa_adv,pin_isa_data[7:0],rreg_system_debug1[7:0],rreg_system_debug1_valid,rreg_system_debug2[7:0],rreg_system_debug2_valid,rreg_system_debug3[7:0],rreg_system_debug3_valid,rreg_system_debug4[7:0],rreg_system_debug4_valid,rreg_system_status[7:0],rreg_system_status_valid,rreg_system_version[47:0],rreg_system_version_valid,rreg_system_rtctime[63:0],rreg_system_rtctime_valid,rreg_system_batteryvalue[15:0],rreg_system_batteryvalue_valid,rreg_system_syncstatus[7:0],rreg_system_syncstatus_valid,rreg_system_syncfrq[31:0],rreg_system_syncfrq_valid,rreg_mem_status[7:0],rreg_mem_status_valid,rreg_mem_data_wr_en,rreg_mem_data_wr_addr[15:0],rreg_mem_data_wr_data[7:0],rreg_ddr_status[7:0],rreg_ddr_status_valid,rreg_ddr_data_wr_en,rreg_ddr_data_wr_addr[15:0],rreg_ddr_data_wr_data[31:0],rreg_series_status[7:0],rreg_series_status_valid,rreg_series_starttime[63:0],rreg_series_starttime_valid,rreg_series_stoptime[63:0],rreg_series_stoptime_valid,rreg_series_maxdata[79:0],rreg_series_maxdata_valid,rreg_series_data_wr_en,rreg_series_data_wr_addr[15:0],rreg_series_data_wr_data[31:0],wreg_system_ctrl[7:0],wreg_system_ctrl_valid,wreg_system_sel_rtc[7:0],wreg_system_sel_rtc_valid,wreg_system_set_rtctime[63:0],wreg_system_set_rtctime_valid,wreg_system_sync_minfrq[15:0],wreg_system_sync_minfrq_valid,wreg_system_sync_max[15:0],wreg_system_sync_max_valid,wreg_system_sync_sel[7:0],wreg_system_sync_sel_valid,wreg_system_ch_sel[7:0],wreg_system_ch_sel_valid,wreg_ddr_ctrl[7:0],wreg_ddr_ctrl_valid,wreg_ddr_addr[31:0],wreg_ddr_addr_valid,wreg_ddr_len[31:0],wreg_ddr_len_valid,wreg_out_ctrl[7:0],wreg_out_ctrl_valid,wreg_out_sel[7:0],wreg_out_sel_valid,wreg_out_time[63:0],wreg_out_time_valid,wreg_out_level[7:0],wreg_out_level_valid,wreg_out_startmode[7:0],wreg_out_startmode_valid,wreg_out_start_targettime[63:0],wreg_out_start_targettime_valid,wreg_out_start_subtime[31:0],wreg_out_start_subtime_valid,wreg_out_start_subnum[31:0],wreg_out_start_subnum_valid,wreg_out_start_subcycle[7:0],wreg_out_start_subcycle_valid,wreg_out_start_trigmode1[31:0],wreg_out_start_trigmode1_valid,wreg_out_start_trigmode2[31:0],wreg_out_start_trigmode2_valid,wreg_out_start_trigmode3[31:0],wreg_out_start_trigmode3_valid,wreg_out_start_trigmode4[31:0],wreg_out_start_trigmode4_valid,wreg_out_trig_threshold_p[15:0],wreg_out_trig_threshold_p_valid,wreg_out_trig_threshold_n[15:0],wreg_out_trig_threshold_n_valid,wreg_out_trig_risetime[15:0],wreg_out_trig_risetime_valid,wreg_out_trig_droptime[15:0],wreg_out_trig_droptime_valid,wreg_out_trig_pulsewidth[15:0],wreg_out_trig_pulsewidth_valid,wreg_out_trig_riseratio[7:0],wreg_out_trig_riseratio_valid,wreg_out_trig_dropratio[7:0],wreg_out_trig_dropratio_valid,wreg_out_trig_rmsvalue[15:0],wreg_out_trig_rmsvalue_valid,wreg_mem_rd_en,wreg_mem_ctrl[7:0],wreg_mem_ctrl_valid,wreg_mem_addr[15:0],wreg_mem_addr_valid,wreg_mem_len[7:0],wreg_mem_len_valid,wreg_mem_clr,wreg_mem_rd_data[7:0],wreg_mem_rd_len[3:0],wreg_ch_zero_cal[15:0],wreg_ch_zero_cal_valid,wreg_ch_sample_rate[15:0],wreg_ch_sample_rate_valid,wreg_ch_sign_handle[7:0],wreg_ch_sign_handle_valid,wreg_ch_main_amp[7:0],wreg_ch_main_amp_valid,wreg_ch_pre_amp[7:0],wreg_ch_pre_amp_valid,wreg_ch_v_amp[7:0],wreg_ch_v_amp_valid,wreg_ch_i_amp[7:0],wreg_ch_i_amp_valid,wreg_ch_noise_comp[7:0],wreg_ch_noise_comp_valid,wreg_ch_noise_amp_cof[15:0],wreg_ch_noise_amp_cof_valid,wreg_ch_noise_delay[7:0],wreg_ch_noise_delay_valid,wreg_ch_start_targettime[63:0],wreg_ch_start_targettime_valid,wreg_ch_start_sustime[31:0],wreg_ch_start_sustime_valid,wreg_ch_start_susnum[31:0],wreg_ch_start_susnum_valid,wreg_ch_start_suscycle[7:0],wreg_ch_start_suscycle_valid,wreg_ch_stop_sustime[31:0],wreg_ch_stop_sustime_valid,wreg_ch_stop_susnum[31:0],wreg_ch_stop_susnum_valid,wreg_ch_stop_suscycle[7:0],wreg_ch_stop_suscycle_valid,wreg_ch_trig_threshold_p[15:0],wreg_ch_trig_threshold_p_valid,wreg_ch_trig_threshold_n[15:0],wreg_ch_trig_threshold_n_valid,wreg_ch_trig_risetime[15:0],wreg_ch_trig_risetime_valid,wreg_ch_trig_droptime[15:0],wreg_ch_trig_droptime_valid,wreg_ch_trig_pulsewidth[15:0],wreg_ch_trig_pulsewidth_valid,wreg_ch_trig_riseratio[7:0],wreg_ch_trig_riseratio_valid,wreg_ch_trig_dropratio[7:0],wreg_ch_trig_dropratio_valid,wreg_ch_trig_rmsvalue[15:0],wreg_ch_trig_rmsvalue_valid,wreg_ch_filter_rd_en,wreg_ch_filter_clr,wreg_ch_filter_rd_data[7:0],wreg_ch_filter_rd_len[3:0],wreg_series_ctrl[7:0],wreg_series_ctrl_valid,wreg_series_data_type[7:0],wreg_series_data_type_valid,wreg_series_sample_cycle[7:0],wreg_series_sample_cycle_valid,wreg_series_comp_ratio[31:0],wreg_series_comp_ratio_valid,wreg_series_comp_num[15:0],wreg_series_comp_num_valid,wreg_series_validmode_data[31:0],wreg_series_validmode_data_valid,wreg_series_start_ddraddr[31:0],wreg_series_start_ddraddr_valid,wreg_series_stop_ddraddr[31:0],wreg_series_stop_ddraddr_valid,wreg_series_startmode[7:0],wreg_series_startmode_valid,wreg_series_star_trigmode1[31:0],wreg_series_star_trigmode1_valid,wreg_series_star_trigmode2[31:0],wreg_series_star_trigmode2_valid,wreg_series_star_trigmode3[31:0],wreg_series_star_trigmode3_valid,wreg_series_star_trigmode4[31:0],wreg_series_star_trigmode4_valid,wreg_series_stopmode[7:0],wreg_series_stopmode_valid,wreg_series_stop_trigmode1[31:0],wreg_series_stop_trigmode1_valid,wreg_series_stop_trigmode2[31:0],wreg_series_stop_trigmode2_valid,wreg_series_stop_trigmode3[31:0],wreg_series_stop_trigmode3_valid,wreg_series_stop_trigmode4[31:0],wreg_series_stop_trigmode4_valid,wreg_series_seek_startime[63:0],wreg_series_seek_startime_valid,wreg_series_seek_zoom[31:0],wreg_series_seek_zoom_valid,wreg_series_seek_datalen[31:0],wreg_series_seek_datalen_valid";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "isa_handle,Vivado 2017.2";
begin
end;
