# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/isa_handle_0.xci
# IP: The module: 'isa_handle_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_get_fifo_generator/isa_get_fifo_generator.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==isa_get_fifo_generator || ORIG_REF_NAME==isa_get_fifo_generator}]

# IP: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_rom_generator/isa_send_rom_generator.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==isa_send_rom_generator || ORIG_REF_NAME==isa_send_rom_generator}]

# IP: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_smallram_generator/isa_send_smallram_generator.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==isa_send_smallram_generator || ORIG_REF_NAME==isa_send_smallram_generator}]

# IP: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_bigram_generator/isa_send_bigram_generator.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==isa_send_bigram_generator || ORIG_REF_NAME==isa_send_bigram_generator}]

# XDC: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_get_fifo_generator/isa_get_fifo_generator.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==isa_get_fifo_generator || ORIG_REF_NAME==isa_get_fifo_generator}] {/U0 }]/U0 ]]

# XDC: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_rom_generator/isa_send_rom_generator_ooc.xdc

# XDC: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_smallram_generator/isa_send_smallram_generator_ooc.xdc

# XDC: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_bigram_generator/isa_send_bigram_generator_ooc.xdc

# IP: C:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/isa_handle_0.xci
# IP: The module: 'isa_handle_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_get_fifo_generator/isa_get_fifo_generator.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==isa_get_fifo_generator || ORIG_REF_NAME==isa_get_fifo_generator}]

# IP: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_rom_generator/isa_send_rom_generator.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==isa_send_rom_generator || ORIG_REF_NAME==isa_send_rom_generator}]

# IP: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_smallram_generator/isa_send_smallram_generator.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==isa_send_smallram_generator || ORIG_REF_NAME==isa_send_smallram_generator}]

# IP: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_bigram_generator/isa_send_bigram_generator.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==isa_send_bigram_generator || ORIG_REF_NAME==isa_send_bigram_generator}]

# XDC: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_get_fifo_generator/isa_get_fifo_generator.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==isa_get_fifo_generator || ORIG_REF_NAME==isa_get_fifo_generator}] {/U0 }]/U0 ]]

# XDC: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_rom_generator/isa_send_rom_generator_ooc.xdc

# XDC: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_smallram_generator/isa_send_smallram_generator_ooc.xdc

# XDC: c:/XD58_test/XD58_Artix_100T_project/Project.srcs/sources_1/ip/isa_handle_0/sources_1/ip/isa_send_bigram_generator/isa_send_bigram_generator_ooc.xdc
